#!/usr/bin/env python3
"""
Build the single-file version of Stickyfoot.

    python3 build.py            -> dist/stickyfoot.html

index.html is the source of truth for what gets included and in what order.
This script walks its <link rel="stylesheet"> and <script src> tags, inlines
each one, and base64s every sprite PNG into a generated SPRITE_DATA table so
the result is one file that runs from anywhere with no assets beside it.

Nothing is minified. The output is meant to stay readable, and to diff sanely.
"""

import base64
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SPRITE_DIR = os.path.join(ROOT, "assets", "sprites")
SPRITE_DATA_JS = os.path.join(ROOT, "js", "art", "sprite-data.js")
SETTINGS_JS = os.path.join(ROOT, "js", "core", "settings.js")
AUDIO_DIR = os.path.join(ROOT, "assets", "audio")
AUDIO_DATA_JS = os.path.join(ROOT, "js", "audio", "audio-data.js")
OUT = os.path.join(ROOT, "dist", "stickyfoot.html")

LOCAL = re.compile(r'^(?!https?:|//)')


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        return f.read()


def generate_settings():
    """Turn settings.json into js/core/settings.js (a plain script, so the dev
    tree works from file:// with no fetch)."""
    raw = read("settings.json")
    try:
        data = json.loads(raw)
    except ValueError as e:
        sys.exit("settings.json is not valid JSON: %s" % e)
    text = (
        '"use strict";\n'
        "/* GENERATED by build.py from settings.json — edit that file, not this one.\n"
        " * Served over http(s) the game re-reads settings.json at boot and applies it\n"
        " * live; from file:// or in the built page these values are what you get.\n"
        " */\n"
        "const SETTINGS = %s;\n" % json.dumps(data, indent=2)
    )
    with open(SETTINGS_JS, "w", encoding="utf-8") as f:
        f.write(text)
    keys = [k for k in data if not k.startswith("_")]
    print("  settings  %s" % ", ".join(keys))
    return text


def generate_audio_data():
    """Turn assets/audio/*.wav into js/audio/audio-data.js.

    Unlike the sprites this is written for development too: a page opened from
    file:// cannot fetch its own .wav files, so the inlined copy is the only way
    to hear anything without a server."""
    manifest = read(os.path.join("js", "audio", "manifest.js"))
    ids = re.findall(r'id:\s*"([^"]+)"', manifest)
    files = re.findall(r'file:\s*"([^"]+)"', manifest)
    if len(ids) != len(files):
        sys.exit("js/audio/manifest.js: every entry needs both an id and a file")

    types = {".wav": "audio/wav", ".ogg": "audio/ogg", ".mp3": "audio/mpeg"}
    lines = ['"use strict";',
             "/* GENERATED by build.py from assets/audio/ — do not edit. */",
             "const AUDIO_DATA = {"]
    total = 0
    for sid, name in zip(ids, files):
        path = os.path.join(AUDIO_DIR, name)
        if not os.path.exists(path):
            sys.exit("missing sound: assets/audio/%s (listed in js/audio/manifest.js)" % name)
        raw = open(path, "rb").read()
        total += len(raw)
        mime = types.get(os.path.splitext(name)[1].lower(), "audio/wav")
        lines.append('  "%s": "data:%s;base64,%s",' % (sid, mime, base64.b64encode(raw).decode("ascii")))
    lines.append("};")
    text = "\n".join(lines) + "\n"
    with open(AUDIO_DATA_JS, "w", encoding="utf-8") as f:
        f.write(text)
    print("  sounds    %d files, %.1f kB raw" % (len(ids), total / 1024.0))
    return text


def generate_sprite_data():
    """Turn assets/sprites/*.png into js/art/sprite-data.js."""
    manifest = read(os.path.join("js", "art", "manifest.js"))
    files = re.findall(r'file:\s*"([^"]+)"', manifest)
    ids = re.findall(r'id:\s*"([^"]+)"', manifest)
    if len(files) != len(ids):
        sys.exit("manifest.js: every entry needs both an id and a file")

    lines = [
        '"use strict";',
        "/* GENERATED by build.py — do not edit.",
        " * Every sprite in manifest.js, inlined so the built file needs no assets folder.",
        " * In development this file is empty and the PNGs are loaded from assets/sprites/.",
        " */",
        "const SPRITE_DATA = {",
    ]
    total = 0
    for sid, name in zip(ids, files):
        path = os.path.join(SPRITE_DIR, name)
        if not os.path.exists(path):
            sys.exit("missing sprite: assets/sprites/%s (listed in manifest.js)" % name)
        raw = open(path, "rb").read()
        total += len(raw)
        b64 = base64.b64encode(raw).decode("ascii")
        lines.append('  "%s": "data:image/png;base64,%s",' % (sid, b64))
    lines.append("};")
    text = "\n".join(lines) + "\n"
    with open(SPRITE_DATA_JS, "w", encoding="utf-8") as f:
        f.write(text)
    print("  sprites   %d files, %.1f kB raw" % (len(ids), total / 1024.0))
    return text


def build():
    print("stickyfoot build")
    settings_js = generate_settings()
    audio_js = generate_audio_data()
    sprite_js = generate_sprite_data()
    html = read("index.html")

    css_count = js_count = 0

    def inline_css(m):
        nonlocal css_count
        href = m.group(1)
        if not LOCAL.match(href):
            return m.group(0)          # leave the web font link alone
        css_count += 1
        return "<style>\n/* %s */\n%s</style>" % (href, read(href))

    def inline_js(m):
        nonlocal js_count
        src = m.group(1)
        if not LOCAL.match(src):
            return m.group(0)
        js_count += 1
        if src.endswith("audio-data.js"): body = audio_js
        elif src.endswith("sprite-data.js"): body = sprite_js
        elif src.endswith("core/settings.js"): body = settings_js
        else: body = read(src)
        return "<script>\n/* ===== %s ===== */\n%s</script>" % (src, body)

    html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_css, html)
    html = re.sub(r'<script src="([^"]+)"></script>', inline_js, html)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)

    left = re.findall(r'(?:src|href)="((?!https?:|//|#)[^"]+)"', html)
    if left:
        print("  WARNING   still referencing local files: %s" % ", ".join(sorted(set(left))))
    print("  css       %d files" % css_count)
    print("  js        %d files" % js_count)
    print("  wrote     dist/stickyfoot.html  (%.0f kB)" % (len(html) / 1024.0))


if __name__ == "__main__":
    build()
